### PR TITLE
Debugger

### LINKED ISSUE #3: Debugger support
One of the [greatest strengths](http://elm-lang.org/blog/the-perfect-bug-report) of Elm architecutre is great debugging experience.

I quickly hacked a POC of integration of this library with [redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension):
elm-ts-debugger

I think I can make a PR here with full support, but the biggest blocker I found is the [recommended usage of non serializable values](https://github.com/gcanti/elm-ts/blob/b4803d0d4679b33b3041d4e03dddfbaddb57d4aa/examples/Http.tsx#L15) from [fp-ts](https://github.com/gcanti/fp-ts) as part of app model. (Please, don't get me wrong, I fully understand their usefulness :) )
I wonder what would be the right solution to this.

### PR DESCRIPTION
**Pull request by StefanoMagrassi**
This PR adds a debugger combinator that "extends" `Html.program` in order to tracks dispatched messages and changes in the `Model` stream.

It tries to connect to the [_Redux DevTool Extension_](https://github.com/zalmoxisus/redux-devtools-extension) and falls back to the standard browser's `console` if it is not available.

It should resolve #3

### CODE REVIEW

**Comment by minedeljkovic** [comment]
I don't know if plan for this PR is to provide all features, but just in case it could be of any help, I uploded this debugger integration for elm-ts 0.4 [https://gist.github.com/minedeljkovic/9c8b0500c98ba81def9111b8f7ef9f86](https://gist.github.com/minedeljkovic/9c8b0500c98ba81def9111b8f7ef9f86)

This supports time travel, import/export, pause, and hot reload (with hacky promise usage) features. 
Basic idea is to produce wrapper elm app, that communicates with redux-devtools-extension through subscriptions.

Disclaimer: solution is extremely unpolished, unflexible, and "just good enough" for basic elm apps (I have even more unpolished version for my production apps, that has support for Navigation elm app). I never had time to polish it enough to make it PR worthy.

**Comment by StefanoMagrassi** [comment]
Thank you @

File: src/Debug/index.ts [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+  (program: Program<Model, Msg, Dom>, renderer: Renderer<Dom>): Observable<Model>
+}
+
+/**
+ * Adds a debugging capability to a generic `Html` `run` function.
+ *
+ * It tracks every `Message` dispatched and resulting `Model` update.
+ * @since 0.5.0
+ */
+export function withDebugger<Model, Msg, Dom>(run: Runner<Model, Msg, Dom>): Runner<Model, Msg, Dom> {
```
Comment (minedeljkovic) [inline src/Debug/index.ts]: if only `run` function is enriched, AFAIK we would not be able to add time travel (and import) support later without breaking the api, since program's update function is needed to fold over changed Msg log

File: src/Debug/redux-devtool.ts [hunk 2]
```diff
@@ -0,0 +1,333 @@
...
+    const end = stagedActionIds.length
+
+    for (let i = start; i < end; i++) {
+      const currentActionId = stagedActionIds[i]
+
+      if (i !== actionIndex && skippedActionIds.indexOf(currentActionId) !== -1) {
+        continue // it's already skipped
+      }
+
+      dispatch(actionsById[currentActionId].action as Msg)
```
Comment (minedeljkovic) [inline src/Debug/redux-devtool.ts]: this will run all Cmds that are produced by this Msg, which can produce new undesirable Msgs during time travelling (see gif below). The only way I am aware of to fix this, (since Task cannot be interpreted in any other way than being run or being ignored) is to somehow ignore these Cmds.
debug

Comment (minedeljkovic) [reply src/Debug/redux-devtool.ts]: More flexible approach could be to give the user information about debuging status, with something like this (sketching only, don't take names too seriously):
```js
export function programWithDebuggerMoreFlexible<Model, Msg, Dom>(
  init: (isTimeTravelling: boolean) => [Model, cmd.Cmd<Msg>],
  update: (isTimeTravelling: boolean) => (msg: Msg, model: Model) => [Model, cmd.Cmd<Msg>],
  view: (model: Model) => Html<Dom, Msg>,
  subscriptions?: (isTimeTravelling: boolean) => (model: Model) => Sub<Msg>
): Program<Model, MsgWithDebug<Model, Msg>, Dom> {
  //...
}

// with default being
export function programWithDebugger<Model, Msg, Dom>(
  init: [Model, cmd.Cmd<Msg>],
  update: (msg: Msg, model: Model) => [Model, cmd.Cmd<Msg>],
  view: (model: Model) => Html<Dom, Msg>,
  subscriptions: (model: Model) => Sub<Msg> = () => none
): Program<Model, MsgWithDebug<Model, Msg>, Dom> {
  return programWithDebuggerMoreFlexible(
    _ => [init[0], Cmd.none],
    _ => (msg: Msg, model: Model) => {
      const [model1, _] = update(msg, model)
      return [model1, Cmd.none]
    },
    view,
    subscriptions && _ => Sub.none
  )
}
```
This way user could choose different strategy form Cmds in time travelling mode

Comment (StefanoMagrassi) [reply src/Debug/redux-devtool.ts]: Thank you very much Milos (I owe you for the hints in your previous reviews :wink:)

I would like to avoid requesting other actions to the user: in my vision the debugging tool usage should be as transparent as possible (only a single line like `const program = process.env.NODE_ENV === 'production' ? ....`)

Furthermor, how should be handled that `isTimeTravelling` flag? The user should inject in the program's source some specific code for the redux devtool? 

I guess that time travelling can be sloppy in many standard redux application with async actions (and effects)

Also, I have to confess that I hugely "take inspiration"  (:smile:) for the `TOGGLE_ACTION` handler - which controls the skip and time travelling features - from the official [MobX integration](https://github.com/zalmoxisus/mobx-remotedev/blob/master/src/monitorActions.js#L22), but I barely understand how it works... :grimacing:

Comment (StefanoMagrassi) [reply src/Debug/redux-devtool.ts]: @minedeljkovic you're right: the extension works correctly with a standard redux app with async actions (`redux-thunk`); [check this codesandbox](https://codesandbox.io/s/hardcore-hill-msds0)

It seems that implementation of the `TOGGLE_ACTION` handler is quite different from the MobX one (it is probably hidden somewhere [here](https://github.com/reduxjs/redux-devtools/blob/master/packages/redux-devtools-instrument/src/instrument.js))

I'm quite stuck on this... Maybe I should re-use "as-is" the implementation in your gist...

Comment (minedeljkovic) [reply src/Debug/redux-devtool.ts]: > I guess that time travelling can be sloppy in many standard redux application with async actions (and effects)

True 😕 , but it can also greatly simplify and speed up QA and customer support process 👍 . In company I work for it became really important part of the process.

These steps are one way to drop cmds comming from time travelling (to reach parity with redux-thunk example):

1. Introduce one more special msg for time travelling:
```js
export type MsgWithDebug<Model, Msg> = Msg | { type: '__DebugUpdateModel__'; payload: Model } | { type: '__DebugApplyMsg__'; payload: Msg }

```
here
https://github.com/gcanti/elm-ts/blob/77e1f5e44dd4de6ec71d536ca4ff460969e9728c/src/Debug/commons.ts#L48

2. Handle this special msg like:
```js
    if ('type' in msg) {
      switch (msg.type) {
        case '__DebugUpdateModel__':
          return [msg.payload, cmd.none]
        case '__DebugApplyMsg__': {
          const [newModel/*, drop cmd*/] = update(msg.payload, model)
          return [newModel, cmd.none]
        }
      }
    }
```
here
https://github.com/gcanti/elm-ts/blob/77e1f5e44dd4de6ec71d536ca4ff460969e9728c/src/Debug/index.ts#L69-L71

3. Dispatch this special msg:
```js
dispatch({ type: '__DebugApplyMsg__', payload: actionsById[currentActionId].action as Msg })
```
here
https://github.com/gcanti/elm-ts/blob/77e1f5e44dd4de6ec71d536ca4ff460969e9728c/src/Debug/redux-devtool.ts#L320

Comment (StefanoMagrassi) [reply src/Debug/redux-devtool.ts]: It looks promising. I'll try right now

Comment (StefanoMagrassi) [reply src/Debug/redux-devtool.ts]: @minedeljkovic it seems working! Please, check it out

Comment (minedeljkovic) [reply src/Debug/redux-devtool.ts]: This is working, now! 👍

**Comment by StefanoMagrassi** [comment]
I think that introdicing a custom export/import function would be out of the scope of this PR.

In the future, maybe we can let the user to provide these function using the connection [configuration object](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#features) and exposing a "tracking" stream of messages

**Comment by StefanoMagrassi** [comment]
@minedeljkovic my idea was to provide a bare minimum integration with the dev-tool, maybe we can collect all this improvements into a separated issue, so we can close this PR, publish the new version and keep going working on it. What do you think about it?

**Comment by minedeljkovic** [comment]
@StefanoMagrassi I'm perfectly OK with that!
All my comments here were in context of:
> I don't know if plan for this PR is to provide all features

My idea was never to block the current level of integration 😉
